### PR TITLE
Ignore test files from npm package

### PR DESCRIPTION
**Pull request by bvwells**
This is to address #34 by removing the test directory from the npm package.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks for the PR, however this will already be the case for the next release due to https://github.com/TooTallNate/node-agent-base/blob/2cb392b31edc4402de1567828b0baf0960c1a05b/package.json#L7-L9.

**Comment by bvwells** [comment]
Thanks for the review @TooTallNate. Any ideas when the next patch release will be?

**Comment by TooTallNate** [comment]
Well it's going to be a major release (due to the rewrite in TypeScript), but I will try to get around to it today.

**Comment by bvwells** [comment]
Great, thanks for you help!

**Pull request closed without merging**
