### PR TITLE
Add typescript declaration

### PR DESCRIPTION
**Pull request by Shinigami92**
2nd solution for #20

### CODE REVIEW

**Comment by Shinigami92** [comment]
The typedefinition is now very rudimentary but works
Let me know what you think about it

in typescript you import the package with
```ts
import { Agent, AgentCallback, AgentOptions } from "agent-base";
import agent = require("agent-base");
```

If you do not like the .d.ts file (s) in your project, I can deploy them via https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Shinigami92** [comment]
I've learned many things about .dts files in the last 3 days ^^
The last commit is based on this: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html

**Comment by Shinigami92** [comment]
If you want you can reference this https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/agent-base in your readme and reject this PR

**Comment by TooTallNate** [comment]
Thanks @Shinigami92!

**Pull request merged**
